name: ml-latest
channels:
    - conda-forge
    - defaults
dependencies:
    - python=3.7
    - numpy=1.16.4
    - uproot
    - tensorflow
    - xrootd
    - scikit-learn
    - matplotlib
    - tqdm
    - pip
    - pip:
      - jupyter-book
      - https://download.pytorch.org/whl/cpu/torch-1.5.0%2Bcpu-cp37-cp37m-linux_x86_64.whl
      - https://download.pytorch.org/whl/cpu/torchvision-0.6.0%2Bcpu-cp37-cp37m-linux_x86_64.whl
      - https://pytorch-geometric.com/whl/torch-1.5.0/torch_scatter-latest%2Bcpu-cp37-cp37m-linux_x86_64.whl
      - https://pytorch-geometric.com/whl/torch-1.5.0/torch_sparse-latest%2Bcpu-cp37-cp37m-linux_x86_64.whl
      - https://pytorch-geometric.com/whl/torch-1.5.0/torch_cluster-latest%2Bcpu-cp37-cp37m-linux_x86_64.whl
      - https://pytorch-geometric.com/whl/torch-1.5.0/torch_spline_conv-latest%2Bcpu-cp37-cp37m-linux_x86_64.whl
      - torch-geometric
